apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: personoversikt
  name: modiapersonoversikt-notifikasjon
  namespace: personoversikt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://modiapersonoversikt-notifikasjon.dev.intern.nav.no
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    max: 4
    min: 2
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  secureLogs:
    enabled: true
  webproxy: true
  env:
    - name: MY_CUSTOM_VAR
      value: "some_value"
    - name: MY_APPLICATION_NAME
      value: ""
